# docker-compose.yml
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/vite.config.js:/app/vite.config.js
    depends_on:
      - backend
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend/.env:/app/.env  
    environment:
      - API_SECRET=your_api_secret_key  
      - REFRESH_SECRET=your_refresh_secret_key  